
class Countries{
   List country=["Nigeria",
    "Ethiopia",
    "Egypt",
    "Congo",
    "Congo, The Democratic Republic of the Congo",
    "Togo",
    "Tanzania, United Republic of Tanzania",
    "South Africa",
    "Kenya",
    "Uganda",
    "Algeria",
    "Sudan",
    "Morocco",
    "Angola",
    "Mozambique",
    "Ghana",
    "Madagascar",
    "Cameroon",
    "Côte d'Ivoire",
    "Niger",
    "Burkina Faso",
    "Mali",
    "Malawi",
    "Zambia",
    "Senegal",
    "Chad",
    "Somalia",
    "Zimbabwe",
    "Guinea",
    "Rwanda",
    "Benin",
    "Burundi",
    "Tunisia",
    "South Sudan",
    "Sierra Leone",
    "Libyan Arab Jamahiriya",
    "Liberia",
    "Central African Republic",
    "Mauritania",
    "Eritrea",
    "Namibia",
    "Gambia",
    "Botswana",
    "Gabon",
    "Lesotho",
    "Guinea-Bissau",
    "Equatorial Guinea",
    "Mauritius",
    "Djibouti",
    "Comoros",
    "Cabo Verde",
    "Sao Tome and Principe",
    "Seychelles"
  ];


}